### ISSUE TITLE
Separate functions into files by functionality

### ISSUE THREAD

**Issue by LILIXU-CCNU** [GreatEmerald/cglops-change-detection#3]
Hi, Dainius and Linlin

Since there will be more and more experiments in this project. It would be nice if there are some corresponding documents to describe the format of input data for a specific R script. And it will be great to reconstruct the functions so that they can be better understood and utilized. 

This is the first github Issue I made, not sure it is work and can be noticed by you guys. Good luck to my first trying. ：）

Best wishes,
Lili

**Comment by GreatEmerald** [comment]
Yes, it works, thanks :)

Can you list the functions more specifically which you find to be lacking? We can use todo lists for each function to keep track of the progress.

**Comment by LILIXU-CCNU** [comment]
hi, great to know you've noticed it. 

Okay, but currently it is hard to say which is lacking. Because the first thing before saying lacking is to clearly understand what we already have.  

An idea just comes into my mind,  maybe we can follow some logic flow to reconstruct some groups to quickly make things easier.  For example,  in general speaking,  we may need scripts about:  cleansing data, preprocessing, models-related, output, visualization, post-statistical analysis....something like that.

But it is just a flash thought and it may only come from my side, I can already feel about how complicated the whole project is. Feel free to ignore me if you think it is not necessary or you already have some wonderful arrangements.

**Comment by GreatEmerald** [comment]
Ah yes, very good idea, to cluster the functions by, well, function :D For sure that's something I'd like to do.

I'll edit the title to reflect the idea better, then.

**Comment by GreatEmerald** [comment]
Fixed as of https://github.com/GreatEmerald/cglops-change-detection/commit/4d3b6e5ae98ed7f814124b23b48624c045503bd5.

Feel free to open new issues for the cases where documentation is lacking :)
